"""created products table and relationship between categories and products

Revision ID: 619493b8cc3b
Revises: b4bc4b870b2f
Create Date: 2025-12-06 18:25:02.993528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619493b8cc3b'
down_revision: Union[str, Sequence[str], None] = 'b4bc4b870b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
